canonical/grafana-agent-operator

- src/prometheus_alert_rules/disk.rules
The metric name `node_filesystem_size_bytes_bytes` appears to be incorrect due to typo. The correct metric name should be `node_filesystem_size_bytes`, and it can be verified from the [source code](https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_common.go#L117) of node exporter.
Fix the typo: `node_filesystem_size_bytes_bytes` -> `node_filesystem_size_bytes`
Prometheus alert rules
N/A
Fix typo in the Prometheus alert rules for disk
> Fix typo in disk.rules

- src/grafana_agent.py
When using Grafana Agent with a logging backend other than Loki, we need to inform that backend about the payloads being compressed using snappy. Loki knows this is the case implicitly, but a third-party won't.
Add a `Content-Encoding` header to all outgoing requests.
This is useful when integrating with, for instance, Vector or Logstash, as they otherwise have no way of knowing about the encoding/compression. 
Properly advertise snappy compression when using the cloud integrator
> fix: properly inform cloud endpoints about the snappy compression

- charmcraft.yaml
- tests/integration/test_juju_info.py
- tox.ini
A 22.04-built charm fails on 20.04.
Split bases, so there's a 1:1 match between build-on and run-on.
Fixes #5.
FIxes #6.
Depends on:
- https://github.com/charmed-kubernetes/pytest-operator/pull/115
Even though charmhub doesn't display the full context correctly yet, if we upload two revisions for two different bases, juju will be able to pick the correct one.
- https://github.com/canonical/charmcraft/issues/1263#issuecomment-1747811709
Note that our current CI does not support multiple *.charm files. Planning to do release manually for now.
> Split bases

- src/charm.py
This ensures that the root fs data will be collected accurately,
since grafana-agent is running in a snap.
Fixes #22
> Add rootfs_path to grafana-agent.yaml

- config.yaml
- src/grafana_agent.py
Closes #14.
Add the metrics scrape timeout as a Juju config option.
> add config option for metrics.global.scrape_timeout

- README.md
- metadata.yaml
These mainly fix things that seem to be leftovers from porting
from the grafana-agent-k8s-operator codebase.
Fixes: #16
Fixes: #21
> Update docs and links

- CONTRIBUTING.md
- src/charm.py
Fix #18 
Currently no subdirectories of `/var/log` are scraped, which also means that juju logs placed in `/var/log/juju` are not sent to Loki. This PR fixes that by scraping `/var/log/**/*log`.
n/a
Deploy the charm, integrate it properly, and watch for logs from `/var/log/juju/` to be sent.
Recursively scrape the logs in `/var/log/`
> Recursively scrape logs in /var/log/

- lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/observability_libs/v0/cert_handler.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/grafana_agent.py
Grafana agent needs to be able to write to multiple backends.
The **grafana-cloud-integrator** charm has been made more generic to support any endpoint which accepts Prometheus remote writes. This PR contains the changes necessary in this charm to make use of that.
> use the now generic cloud integrator charm

- src/grafana_dashboards/grafana-agent-node-exporter-quickstart_rev2.json
- Use the prometheus datasource variable as expected by the COS tools.
- Remove the old instance and job filter variables:
- instance is a long generated string; use juju_unit instead (and not a multi-select for juju_unit, as this dashboard is designed to be used on one instance at a time)
- job is also long and generated so we can't hard code it any more
Fixes #24
> Fix Grafana Agent Node Exporter Quickstart dash

- src/prometheus_alert_rules/oomkill.rule
Closes #50 
Change the oomkill.rule expression to use 1h instead of 1m for the duration.
Change the out of memory alert expression to use 1h instead of 1m for the duration.
> Change the expression of the oomkill.rule to use 1h

- requirements.txt
Pin cryptography version to the version prior to upstream changing the build dep of `openssl` to `3.2.1`. See https://cryptography.io/en/latest/changelog/#v42-0-2.
> fix: cryptography issue

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/pull_request_template.md
- .jujuignore
- charmcraft.yaml
- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/grafana_agent.py
Telemetry reaches prom/loki with incorrect labels.
- Render instance name from fqdn instead of topology identifier.
- Add cos-tool, similar to https://github.com/canonical/grafana-agent-k8s-operator/pull/277.
Fixes #60.
Drive-by fixes:
- Fetch-lib
- Add `.wokeignore` to `.jujuignore`
- Update issue templates
Deploy something like this bundle:
```yaml
series: jammy
saas:
loki:
url: microk8s:admin/pebnote.loki
loki2:
url: microk8s:admin/pebnote.loki2
prom:
url: microk8s:admin/pebnote.prom
applications:
cp:
charm: local:cos-proxy-1
num_units: 1
ga:
charm: local:grafana-agent-3
nrpe:
charm: nrpe
channel: edge
revision: 117
ub:
charm: ubuntu
channel: edge
revision: 24
num_units: 1
ub2:
charm: ubuntu
channel: edge
revision: 24
num_units: 1
zk:
charm: zookeeper
channel: 3/edge
revision: 126 …
```
> Fix label treatment of related charms

- src/charm.py
- tests/scenario/test_machine_charm/test_scrape_configs.py
Closes #56.
Instead of iterating over log slots in relation data, we iterate over fstab entries; this way, the behavior for 1. multiple logs slots being defined and 2. multiple paths in the same log slot, should be correct.
Deploy grafana-agent and relate it to [the PostgreSQL charm](https://github.com/canonical/postgresql-operator) or a charm with multiple slots.
---
This has been manually tested with the PostgreSQL charm and it produces all the scrape jobs correctly.
> iterate over fstab entries instead of relation data

- src/grafana_agent.py
Closes #100.
Simply return the FQDN as it is, instead of doing the regex substitution, since label values can be any unicode character.
> remove regex in _instance_name

- lib/charms/observability_libs/v0/cert_handler.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- src/grafana_agent.py
- tox.ini
Grafana agent must also work with juju 2.9, but certhandler v1 uses secrets.
Switch back to certhandler v0.
This reverts commit 0cfca69ac1b60cec4761b6817830e93a743bec7c.
Fixes #105.
In tandem with:
- https://github.com/canonical/observability-libs/pull/88
```mermaid
graph LR
subgraph lxd/juju-2.9.49
ubuntu --- grafana-agent
end
subgraph microk8s/juju-3.4.2
prometheus --- self-signed-certificates
traefik --- self-signed-certificates
prometheus --- traefik
end
grafana-agent --- self-signed-certificates
grafana-agent --- prometheus
```
"cos" model, Juju 3.4:
```yaml
bundle: kubernetes
saas:
applications:
prom:
charm: prometheus-k8s
channel: latest/edge
revision: 182
base: ubuntu@20.04/stable
scale: 1
trust: true
ssc:
charm: self-signed-certificates
channel: latest/edge
revision: 137
scale: 1 …
```
> Revert "bump cert_handler to v1 (#94)"

- src/charm.py
- src/grafana_agent.py
Fix #55 
Add the juju_charm and job label to fix alert rule matching.
Before
After
Example alert rule
n/a
1. `juju deploy github-runner` (or any compatible machine charm)
2. `juju integrate github-runner grafana-agent`
3. Make sure the logs contain the `juju_charm=grafana-agent` label so that the alert expressions are matched.
> Add juju_charm label to logs

- src/snap_management.py
- tox.ini
Bumps workload version of grafana-agent to 0.40.4 for both amd64 and arm64.  
Reasons:
* This change means that grafana-agent-operator and grafana-agent-k8s-operator support the same grafana-agent workload version.  Previous to this change, grafana-agent-operator's different architectures also used different workload versions (0.35.x for amd64, 0.39.x for arm64)
* https://github.com/canonical/grafana-agent-k8s-operator/issues/296 identified a possible issue with an older grafana-agent version
Should be covered by existing tests.  If workload deploys successfully it should be working as expected.
> bump version of grafana-agent to 0.40.4 on all architectures

- src/prometheus_alert_rules/disk.rules
In a case that a disk breaks and is not recognized anymore by the kernel, the metrics of a specific device will stop from been collected.
Create a Prometheus alert rule to operators be able to notice that a physical disk was removed.
Virtual disks don't have the model, serial and wwn, so those fields are used to just target physical ones. If a physical disk is removed, the alert will continue to fire as long as the disk remains missing and up to 30 days from the removal.
> Add physical disk removal alert

- tests/integration/test_juju_info_cos_agent.py
Fixes #161
Previously, hardware-observer showed a metric down during tests, resulting in CI failures.  This change pins to a known working version of hardware observer to resolve the failing CI.
See #161
If CI passes, fix is successful
-
Part of OPENG-2554
> fix: pin hardware-obsever to rev70 in integration tests

- lib/charms/grafana_agent/v0/cos_agent.py
Partially fixes https://github.com/canonical/grafana-agent-operator/issues/114, where the `cos_agent` charm library is not compatible with charms or other charm libraries that use Pydantic v2.
Pydantic v2 provides full v1 compatibility via the `pydantic.v1` namespace. When it is detected that the environment is using Pydantic v2, switch to using that instead of importing Pydantic v2.
This should have no impact on any existing charms.
> Make `cos_agent` charm library compatible with Pydantic v1/v2

- lib/charms/grafana_agent/v0/cos_agent.py
After https://github.com/canonical/grafana-agent-operator/pull/156, changes in cos_agent done to support both pydantic versions fail with
```
File "/home/ubuntu/grafana-agent-operator/lib/charms/grafana_agent/v0/cos_agent.py", line 333, in <module>
if int(pydantic.version.VERSION.split(".")[0]) < 2:  # type: ignore
AttributeError: module 'pydantic.v1' has no attribute 'version'
```
Remove conditional import of `pydantic.v1` and adjust the models instead to support both Pydantic versions.
1. Run `tox -r` on the current code
2. To check how it behaves with pydantic v2, unpin pydantic in requirements.txt and run `tox -r` again. One scenario test will be failing as it creates a raw model, other than that everything should still work.
> Fix pydantic models by dropping importing v1

- src/charm.py
- tests/scenario/test_machine_charm/test_alert_labels.py
- tests/scenario/test_machine_charm/test_multiple_subordinates.py
- tests/scenario/test_machine_charm/test_relation_priority.py
- tests/scenario/test_machine_charm/test_scrape_configs.py
- tests/scenario/test_machine_charm/test_tracing_configuration.py
- tests/scenario/test_setup_statuses.py
- tests/scenario/test_start_statuses.py
- tests/unit/test_fstab_parsing.py
- tests/unit/test_relation_status.py
- tests/unit/test_update_status.py
Not sure what has changed, but linting now fails within this repo after a ruff bump.  Fixing that here
Running `tox -e fmt`
> fix: sorting of imports to match ruff 0.6.x

- lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
- tests/unit/test_cloud_integration.py
This PR fixes [this issue](https://github.com/canonical/grafana-cloud-integrator/issues/12) where grafana-agent is not correctly setting its prometheus_remote_write settings for non-leader units, leading to non-leader units not properly writing their data to prometheus
The issue is caused by leadership guards in the grafana-cloud-integrator library's `GrafanaCloudConfigRequirer` relation handling.  Specifically, it does nothing on relation changed/relation broken events.  
The solution here is:
* add tests that demonstrate the prometheus_remote_write settings are written to config for both leader and non-leader units
* bump the grafana-cloud-integrator lib to fix the issue
```bash
juju add-model ga1
juju deploy ubuntu -n 2
juju deploy grafana-agent --channel=latest/edge
juju deploy …
```
> fix: configure prometheus_remote_write config for non-leader

- lib/charms/grafana_agent/v0/cos_agent.py
COS agent documentation was missing references to `tracing_protocols` parameter that can be passed to `COSAgentProvider`.
Add information about these protocols.
> Add tracing_protocols to cos-agent documentation

- charmcraft-22.04.yaml
- pyproject.toml
- src/charm.py
- src/grafana_agent.py
- src/snap_management.py
- tests/integration/test_classic_config_flag.py
- tests/integration/test_juju_info_cos_agent.py
- tests/scenario/test_machine_charm/conftest.py
- tests/scenario/test_machine_charm/test_alert_labels.py
- tests/scenario/test_machine_charm/test_multiple_subordinates.py
- tests/scenario/test_machine_charm/test_relation_priority.py
- tests/scenario/test_machine_charm/test_scrape_configs.py
- tests/scenario/test_machine_charm/test_tracing_configuration.py
- tests/unit/test_cloud_integration.py
- tests/unit/test_relation_status.py
- tests/unit/test_update_status.py
- tox.ini
We want to switch to using the classically confined snap by default, but continue to have strict as an option. This is because the strictly confined snap has problems getting everything it needs from the system.
fixes #52
fixes #23 
Added a new "classic_snap" config option.
Fiddle with the "classic_snap" variable. You can use `snap info --verbose grafana-agent | grep confinement` to check the confinement of the currently installed snap.
Now uses the classically confined grafana-agent snap.
> Classic snap

- src/charm.py
Since we [have learn something that was not documented in Grafana docs](https://github.com/grafana/agent/pull/7026), which is that `grafana-agent` is not able to forward `structured_metadata` coming from `promtail` (or another `grafana-agent`) to `loki`
```
promtail --> grafana-agent --> loki
```
We are removing `structured_metadata` because the pipeline is not reliable. An administrator may wrongly think that because `promtail` sends `structured_metadata` it will reach `loki` when this is not always true.
> remove structured_metadata

- charmcraft-22.04.yaml
- charmcraft-24.04.yaml
- src/grafana_agent.py
- tests/scenario/test_machine_charm/test_tracing_configuration.py
Grafana-agent charm passes all traces to the tracing backend as it doesn't have any downsampling configuration.
Add a sampling policy with three config variables, setting up sampling strategies for charm traces, workload traces and errors.
Grafana agent uses tail sampling processor from opentelemetry-collector, its reference is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.96.0/processor/tailsamplingprocessor
Tandem PR: https://github.com/canonical/grafana-agent-k8s-operator/pull/319
Run the following bundle in a machine model, using mysql-operator from [this branch](https://github.com/mmkay/mysql-operator/tree/tracing-in-cos-agent):
```
default-base: ubuntu@22.04/stable
saas:
prometheus-receive-remote-write:
url: …
```
> Traces downsampling policy

- src/charm.py
Start collecting GPU metrics for monitoring data centers that uses AMD GPUs
Enable the `drm` collector that is disabled by default
Even that not all servers have AMD GPUs the impact in terms of performance for time of collecting metrics wasn't perceptive.
On a machine that does not have AMD GPUs it will barely increase the number of metrics:
```shell
node_drm_card_info{card="card1",memory_vendor="",power_performance_level="",unique_id="",vendor="amd"} 1
node_drm_card_info{card="card2",memory_vendor="",power_performance_level="",unique_id="",vendor="amd"} 1
node_drm_gpu_busy_percent{card="card1"} 0
node_drm_gpu_busy_percent{card="card2"} 0
node_drm_memory_gtt_size_bytes{card="card1"} 0
node_drm_memory_gtt_size_bytes{card="card2"} 0
node_drm_memory_gtt_used_bytes{card="card1"} 0 …
```
> Add drm collector to start having metrics from AMD GPUs

- lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
- tox.ini
This PR fixes #203
Pack the charm, and deploy this bundle:
```yaml
default-base: ubuntu@22.04/stable
applications:
agent:
charm: local:grafana-agent-0
grafana-cloud-integrator:
charm: grafana-cloud-integrator
channel: latest/edge
revision: 21
num_units: 1
to:
- "1"
options:
loki-url: http://loki.com
password: Password
username: Username
constraints: arch=amd64
ubuntu:
charm: ubuntu
channel: latest/stable
revision: 25
num_units: 3
to:
- "2"
- "3"
- "4"
constraints: arch=amd64
storage:
block: loop,100M
files: rootfs,100M
machines:
"1":
constraints: arch=amd64
"2":
constraints: arch=amd64
"3":
constraints: arch=amd64
"4":
constraints: arch=amd64
relations:
- - ubuntu:juju-info
- agent:juju-info
- - grafana-cloud-integrator:grafana-cloud-config
- agent:grafana-cloud-config
```
then, verify …
> update cloud_config_requirer lib

- lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py
- src/charm.py
- src/grafana_agent.py
This PR partially is in tandem with the PR https://github.com/canonical/grafana-cloud-integrator/pull/21 and should be merged after.
It also fixes (partially) https://github.com/canonical/grafana-cloud-integrator/issues/18 (I'm also opening a PR in the k8s charm).
⚠️ Do NOT merge before the other one, it contains the (yet) unreleased version of the `cloud_config_requirer` library.
**grafana-cloud-integrator#21** (the PR for the CA issue) is addressed by saving the CA coming from relation data to file, and then calling `update-ca-certificates` as usual. We do this on the custom `cloud-config-available` event, which is emitted whenever there is a relation joined/changed/broken involving the cloud-integrator relation.
**grafana-cloud-integrator#18** (the config issue) is solved by populating …
> feat: support external ca from cloud-integrator

- src/prometheus_alert_rules/oomkill.rules
Alert rules won't reach Prometheus because they fail validation. Specifically, the group name `HostMemory` is used both in `oomkill.rules` and in `memory.rules`.
Change the group name of the `oomkill.rules` file, so it doesn't clash with the one in `memory.rules`.
> fix: remove group name repetition from alerts

- charmcraft.yaml
grafana agent charm may have quite some reldata to pipe through, and updating many relations may take some time, because the pyyaml we end up using isn't optimized.
Use a binary pyyaml package.
In tandem with https://github.com/canonical/grafana-agent-k8s-operator/pull/332.
https://github.com/canonical/cos-proxy-operator/pull/150
>  Use a binary PyYAML package

- pyproject.toml
`tox -e fmt` passes without changes, but `tox -e lint` [fails](https://github.com/canonical/grafana-agent-operator/actions/runs/11978290330).
Specify python target version for ruff.
https://github.com/astral-sh/ruff/pull/13896
> Specify default py version for ruff

- src/prometheus_alert_rules/disk.rules
This check does not make a lot of sense as a canned alert rule as  it is way too context dependent. Resolves #42 
The current disk IO alerts are set to too low of a threshold. 
Remove the alert rules
As suggested in #42, these alerts are far too context dependent to be part of the canned alert rules.
> fix(alerting): Remove alert rules for detecting high disk read/write

- lib/charms/grafana_agent/v0/cos_agent.py
Bump LIBPATCH because [this commit](https://github.com/canonical/grafana-agent-operator/commit/00a71be918731428657f4e1f482386b17b5e0549) was directly pushed to main by mistake.
> chore: bump LIBPATCH for cos_agent

- tests/scenario/test_machine_charm/conftest.py
- tests/scenario/test_machine_charm/test_tracing_configuration.py
In scenario test runs, a significant number of warnings (and some error logs) came from the fact that charm tracing was enabled even though there isn't anything charm traces can be sent to. 
```
WARNING  tracing:charm_tracing.py:658 <class 'charm.GrafanaAgentMachineCharm'>._server_cert is None; sending traces over INSECURE connection.
WARNING  opentelemetry.trace:__init__.py:537 Overriding of current TracerProvider is not allowed
WARNING  opentelemetry.sdk.trace.export:__init__.py:213 Already shutdown, dropping span.
WARNING  opentelemetry.sdk.trace.export:__init__.py:213 Already shutdown, dropping span.
WARNING  opentelemetry.sdk.trace.export:__init__.py:213 Already shutdown, dropping span.
WARNING  opentelemetry.sdk.trace.export:__init__.py:213 Already shutdown, dropping span.
WARNING …
```
> Remove log pollution from charm tracing in scenario tests

- charmcraft.yaml
- src/charm.py
Closes #48.
Grafana Agent scrapes all the log files under `/var/log` via a scrape job that defines `__path__: /var/log/**/*.log`. The scrape job definition allows defining a `__path_exclude__` key at the same level, allowing a Glob pattern matching to exclude files from the scrape.
This PR allows users to set that `__path_exclude__` key with a config option.
1. Deploy Grafana Agent (with `juju config agent exclude_files="some/glob") + Zookeeper on machine, Loki + Traefik + Grafana (to use as Loki UI) on k8s.
2. Create a file under the excluded path.
3. Verify the log doesn't appear in Loki.
> feat: add exclude-list for logs in /var/log

- lib/charms/grafana_agent/v0/cos_agent.py
- src/prometheus_alert_rules/memory.rules
- tests/scenario/test_alert_labels.py
Closes #41.
> [!warning]
> I had to bump the `cos_agent` library because of a linting error which was auto-fixed by `tox -e fmt`.
Modify the alert expression as detailed in the issue. The expression was flipped because there is a `MemFree_bytes` metric, but not a `MemUsed_bytes` one.
TL;DR (see comments in the yaml below):
```yaml
expr: |
100 * avg_over_time(node_memory_MemFree_bytes[1m]) /
(
avg_over_time(node_memory_MemTotal_bytes[1m])
- avg_over_time(node_memory_Hugetlb_bytes[1m])
) < 10
```
Here's a visual representation:
🔴 Pre-allocated HugePages memory (`node_memory_Hugetlb_bytes`)
🟣 Memory used *outside of HugePages* (`node_memory_MemTotal_bytes - node_memory_Hugetlb_bytes`)
🔵 Available memory (`node_memory_MemFree_bytes`)
🔴 + 🟣 = `node_memory_MemTotal_bytes`
**Memory:** …
> feat: add hugepages into the HostMemoryFull alert expression

- src/prometheus_alert_rules/disk.rules
[grafana-agent-k8s#331](https://github.com/canonical/grafana-agent-k8s-operator/issues/331)
Update the alert to include all mountpoints (removing the `mountpoint~="/"` filter), but excluding irrelevant mountpoints:
- `fstype: fuse.lxcfs` is always NaN (confirmed by the LXD team)
- `fstype: fuse.snapfuse` is always 100%
- `/run`, `/proc`, and `/dev` are not relevant
> fix: apply HostDiskSpace alert to all relevant mountpoints

- charmcraft.yaml
- lib/charms/grafana_agent/v0/cos_agent.py
- tests/scenario/test_alert_labels.py
Closes #208.
In tandem with: https://github.com/canonical/grafana-agent-k8s-operator/pull/341.
Fix the `cos-tool` permissions according to the linked issue (removing the *write* permission from *others*).
> [!warning]
> I had to bump the `cos_agent` library because of a linting error which was auto-fixed by `tox -e fmt`.
We change the `cos-tool` permissions with `path.chmod(0o777)` in multiple places:
- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
We need three PRs in Prometheus, Loki and Grafana to fix those libraries:
- https://github.com/canonical/prometheus-k8s-operator/pull/664
- …
> fix: update cos-tool permissions to adhere to cis hardening rules

- lib/charms/grafana_agent/v0/cos_agent.py
Deploying two grafana agent instances on the same VM is not supported, but we cannot prevent it.
One way this could be prevented indirectly is if the principal charm has a "limit: 1" for the cos-agent relation. 
Add note in docstring encouraging users to add a "limit: 1".
> Add note about limit: 1 for the provider.

- lib/charms/grafana_agent/v0/cos_agent.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- requirements.txt
- tests/scenario/test_models.py
- tests/scenario/test_peer_relation.py
- tests/scenario/test_relation_priority.py
- tox.ini
In tandem with:
- https://github.com/canonical/grafana-k8s-operator/pull/363
- https://github.com/canonical/cos-lib/pull/114
- https://github.com/canonical/cos-proxy-operator/pull/175
Tested with the new lib :
```mermaid
graph LR
ubuntu --- hardware-observer --- grafana-agent ---|CMR| grafana
ubuntu2 --- hardware-observer
ubuntu --- grafana-agent
ubuntu2 --- grafana-agent
```
```yaml
default-base: ubuntu@22.04/stable
saas:
graf:
url: microk8s:admin/graf.graf
applications:
ga:
charm: local:grafana-agent-11
ho:
charm: local:hardware-observer-0
resources:
perccli-deb: 1
sas2ircu-bin: 1
sas3ircu-bin: 1
storcli-deb: 1
ub:
charm: ubuntu
channel: latest/stable
revision: 25
num_units: 2
ub2:
charm: ubuntu
channel: latest/stable
revision: 25
num_units: 1
relations:
- - ho:general-info
- …
```
> Automatically overwrite dashboard UIDs with a prescribed naming pattern

- src/grafana_agent.py
- tests/unit/conftest.py
Closes https://github.com/canonical/grafana-agent-operator/security/advisories/GHSA-4v68-8hj7-x63r
Related: https://github.com/canonical/operator/issues/1521
> fix: permissions in created files

- src/prometheus_alert_rules/memory.rules
Closes #247.
Use `MemAvailable` instead of `MemFree` in the alert.
> **MemFree_bytes**: Theamount of physical RAM left unused by the system.
> **MemAvailable_bytes**: An estimate of how much memory is available for starting new applications, without swapping.
> fix: have HostMemoryFull alert use MemAvailable instead of MemFree

- charmcraft.yaml
The charm gets built using the old, slow, somewhat-weird `charm` plugin
This switches the charm to use the new uv plugin available since Charmcraft 3.3. Due to https://github.com/astral-sh/uv/issues/11963 it simply uses binaries, but I've included a way to build entirely from source.
Sparked by a question by @sed-i in the Charmcraft matrix channel
Ensure that the packed charm works the same as before :-)
This includes ensuring that it uses the optimised C-compiled version of pyyaml.
n/a
On my machine, the charm as-is packs all three amd64 platforms from scratch in under 3 minutes:
```terminal
$ time charmcraft pack
Packed grafana-agent_ubuntu@20.04-amd64.charm
Packed grafana-agent_ubuntu@22.04-amd64.charm
Packed grafana-agent_ubuntu@24.04-amd64.charm
real    2m57.678s
user    0m9.707s
sys …
```
> feat(charmcraft): switch to the uv plugin

- charmcraft.yaml
The `charmcraft.yaml` file unnecessarily installs and uses `curl` rather than using the `dump` plugin directly
This grabs the `cos-tool` release directly into the dump plugin rather than installing curl and using that. The net effect should be the same.
I guess my specialised knowledge is the details about how parts work.
Ensure that `cos-tool-*` in the charm still has the same permissions (looks like it to me):
n/a
> feat(charmcraft): get cos-tool directly

- charmcraft.yaml
- src/charm.py
- tests/unit/test_alert_labels.py
This PR fixes: https://github.com/canonical/cos-configuration-k8s-operator/issues/113
In this PR we implement a new config option for grafana-agent, `extra_alert_labels`
```
Comma separated key-value pairs of labels to be added to all alerts.
This could be useful for differentiating between staging and production environments.
```
[Ref](https://github.com/canonical/cos-configuration-k8s-operator/issues/113): 
> COS currently uses a model in which prometheus alerts are created and managed by the charm developers.
However, this is a generalist solution that doesn't apply to all teams, all environments or all situations.
> 
> Sometimes, we want to add or remove a label depending on the environment stage (production/staging/dev).
Or maybe we want to prioritize business critical environments, …
> feat: add extra_alert_labels as a juju config option

- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/operator_libs_linux/v2/snap.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- src/charm.py
- src/grafana_agent.py
- tests/unit/test_alert_labels.py
As part of `Backport the extra_alert_labels feature to track/1` and other similar issues, we added a new config option for extra alert labels, but those labels are not being added to the [generic alert rules](https://github.com/canonical/cos-lib/blob/6cd3769727419f50018994591a90c0024542389b/src/cosl/rules.py#L114).
~~This is likely because in grafana-agent, we do not pass the `extra_alert_labels` to [the cos-agent lib which is handling the generic alert rules](https://github.com/canonical/grafana-agent-operator/blob/7684e2340f538ec42cd3e0d0be253a43c645058c/src/charm.py#L228). This would likely need to be done for other places we inject generic alerts like in [prom-remote-write](https://github.com/canonical/grafana-agent-operator/blob/7684e2340f538ec42cd3e0d0be253a43c645058c/src/grafana_age …
> fix: add extra_alert_labels for injected generic alerts
